apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: modern-cicd
resources:
  - ../../base
images:
  - name: APP_IMAGE
    newName: 281502313983.dkr.ecr.ap-southeast-1.amazonaws.com/modern-k8s-cicd-app
    newTag: bootstrap
